package com.gridnine.bof.server.rules

#Применимые ГДС для letaem
rule "rule 1"
salience -1
	when
		proxy: com.gridnine.bof.server.rules.RuleProxy (
			proxyType == "GDS_PARAMETERS"
		)
		propSet: com.gridnine.bof.server.gds.rules.proxy.GDSParametersProperties(
			propSet.partnerCode == "letaem" || == "unifest2"
		) from proxy.getPropertySet()
	then
		if(!(proxy.getAppliedRuleCategories().contains("additional-search-oneways") || proxy.getAppliedRuleCategories().contains("applicable-GDS"))){
		   if(!proxy.getAppliedRuleCategories().contains("applicable-GDS")){
			((com.gridnine.bof.server.gds.rules.proxy.GDSParametersActions) proxy.getActionSet()).addApplicableGDS("UNIFEST");
			proxy.getAppliedRuleCategories().add("applicable-GDS");
			if(proxy.getAppliedRuleCategories().contains("additional-search-oneways") || proxy.getAppliedRuleCategories().contains("applicable-GDS")){
				proxy.getAppliedRules().add("24422FC9-C45C-4990-9DE8-42F7AF3AD377");
				proxy.setRoundingMode("NONE");
				proxy.setRoundingValue("V_1");
			}
		   }
		   if(!proxy.getAppliedRuleCategories().contains("additional-search-oneways")){
			((com.gridnine.bof.server.gds.rules.proxy.GDSParametersActions) proxy.getActionSet()).setSearchOW(false);
			proxy.getAppliedRuleCategories().add("additional-search-oneways");
			if(proxy.getAppliedRuleCategories().contains("additional-search-oneways") || proxy.getAppliedRuleCategories().contains("applicable-GDS")){
				proxy.getAppliedRules().add("24422FC9-C45C-4990-9DE8-42F7AF3AD377");
				proxy.setRoundingMode("NONE");
				proxy.setRoundingValue("V_1");
			}
		   }
		}
end

#Применимые ГДС для qunar
rule "rule 2"
salience -2
	when
		proxy: com.gridnine.bof.server.rules.RuleProxy (
			proxyType == "GDS_PARAMETERS"
		)
		propSet: com.gridnine.bof.server.gds.rules.proxy.GDSParametersProperties(
			propSet.partnerCode == "qunar"
		) from proxy.getPropertySet()
	then
		if(!(proxy.getAppliedRuleCategories().contains("additional-search-oneways") || proxy.getAppliedRuleCategories().contains("applicable-GDS"))){
		   if(!proxy.getAppliedRuleCategories().contains("applicable-GDS")){
			((com.gridnine.bof.server.gds.rules.proxy.GDSParametersActions) proxy.getActionSet()).addApplicableGDS("UNIFEST");
			proxy.getAppliedRuleCategories().add("applicable-GDS");
			if(proxy.getAppliedRuleCategories().contains("additional-search-oneways") || proxy.getAppliedRuleCategories().contains("applicable-GDS")){
				proxy.getAppliedRules().add("176452FF-0635-4DF2-9461-2C0B4975AA7A");
				proxy.setRoundingMode("NONE");
				proxy.setRoundingValue("V_1");
			}
		   }
		   if(!proxy.getAppliedRuleCategories().contains("additional-search-oneways")){
			((com.gridnine.bof.server.gds.rules.proxy.GDSParametersActions) proxy.getActionSet()).setSearchOW(false);
			proxy.getAppliedRuleCategories().add("additional-search-oneways");
			if(proxy.getAppliedRuleCategories().contains("additional-search-oneways") || proxy.getAppliedRuleCategories().contains("applicable-GDS")){
				proxy.getAppliedRules().add("176452FF-0635-4DF2-9461-2C0B4975AA7A");
				proxy.setRoundingMode("NONE");
				proxy.setRoundingValue("V_1");
			}
		   }
		}
end

#Применимые ГДС для priceSabre
rule "rule 3"
salience -3
	when
		proxy: com.gridnine.bof.server.rules.RuleProxy (
			proxyType == "GDS_PARAMETERS"
		)
		propSet: com.gridnine.bof.server.gds.rules.proxy.GDSParametersProperties(
			propSet.partnerCode == "priceSabre"
		) from proxy.getPropertySet()
	then
		if(!(proxy.getAppliedRuleCategories().contains("additional-search-oneways") || proxy.getAppliedRuleCategories().contains("applicable-GDS"))){
		   if(!proxy.getAppliedRuleCategories().contains("applicable-GDS")){
			((com.gridnine.bof.server.gds.rules.proxy.GDSParametersActions) proxy.getActionSet()).addApplicableGDS("UNIFEST");
			proxy.getAppliedRuleCategories().add("applicable-GDS");
			if(proxy.getAppliedRuleCategories().contains("additional-search-oneways") || proxy.getAppliedRuleCategories().contains("applicable-GDS")){
				proxy.getAppliedRules().add("7ECF341F-6648-4D16-B480-09D8E87F6358");
				proxy.setRoundingMode("NONE");
				proxy.setRoundingValue("V_1");
			}
		   }
		   if(!proxy.getAppliedRuleCategories().contains("additional-search-oneways")){
			((com.gridnine.bof.server.gds.rules.proxy.GDSParametersActions) proxy.getActionSet()).setSearchOW(false);
			proxy.getAppliedRuleCategories().add("additional-search-oneways");
			if(proxy.getAppliedRuleCategories().contains("additional-search-oneways") || proxy.getAppliedRuleCategories().contains("applicable-GDS")){
				proxy.getAppliedRules().add("7ECF341F-6648-4D16-B480-09D8E87F6358");
				proxy.setRoundingMode("NONE");
				proxy.setRoundingValue("V_1");
			}
		   }
		}
end

#Применимые ГДС для pricePortbilet
rule "rule 4"
salience -4
	when
		proxy: com.gridnine.bof.server.rules.RuleProxy (
			proxyType == "GDS_PARAMETERS"
		)
		propSet: com.gridnine.bof.server.gds.rules.proxy.GDSParametersProperties(
			propSet.partnerCode == "pricePortbilet"
		) from proxy.getPropertySet()
	then
		if(!(proxy.getAppliedRuleCategories().contains("additional-search-oneways") || proxy.getAppliedRuleCategories().contains("applicable-GDS"))){
		   if(!proxy.getAppliedRuleCategories().contains("applicable-GDS")){
			((com.gridnine.bof.server.gds.rules.proxy.GDSParametersActions) proxy.getActionSet()).addApplicableGDS("PORTBILET");
			proxy.getAppliedRuleCategories().add("applicable-GDS");
			if(proxy.getAppliedRuleCategories().contains("additional-search-oneways") || proxy.getAppliedRuleCategories().contains("applicable-GDS")){
				proxy.getAppliedRules().add("7C0ACD23-5504-4640-A332-EF3F38E08AA1");
				proxy.setRoundingMode("NONE");
				proxy.setRoundingValue("V_1");
			}
		   }
		   if(!proxy.getAppliedRuleCategories().contains("additional-search-oneways")){
			((com.gridnine.bof.server.gds.rules.proxy.GDSParametersActions) proxy.getActionSet()).setSearchOW(false);
			proxy.getAppliedRuleCategories().add("additional-search-oneways");
			if(proxy.getAppliedRuleCategories().contains("additional-search-oneways") || proxy.getAppliedRuleCategories().contains("applicable-GDS")){
				proxy.getAppliedRules().add("7C0ACD23-5504-4640-A332-EF3F38E08AA1");
				proxy.setRoundingMode("NONE");
				proxy.setRoundingValue("V_1");
			}
		   }
		}
end

#Применимые ГДС для pulkovo
rule "rule 5"
salience -5
	when
		proxy: com.gridnine.bof.server.rules.RuleProxy (
			proxyType == "GDS_PARAMETERS"
		)
		propSet: com.gridnine.bof.server.gds.rules.proxy.GDSParametersProperties(
			propSet.partnerCode == "pulkovo"
		) from proxy.getPropertySet()
	then
		if(!(proxy.getAppliedRuleCategories().contains("additional-search-oneways") || proxy.getAppliedRuleCategories().contains("applicable-GDS"))){
		   if(!proxy.getAppliedRuleCategories().contains("applicable-GDS")){
			((com.gridnine.bof.server.gds.rules.proxy.GDSParametersActions) proxy.getActionSet()).addApplicableGDS("GALILEO");
			proxy.getAppliedRuleCategories().add("applicable-GDS");
			if(proxy.getAppliedRuleCategories().contains("additional-search-oneways") || proxy.getAppliedRuleCategories().contains("applicable-GDS")){
				proxy.getAppliedRules().add("A2F077E2-9EEC-4D14-A20C-4F2B469798B8");
				proxy.setRoundingMode("NONE");
				proxy.setRoundingValue("V_1");
			}
		   }
		   if(!proxy.getAppliedRuleCategories().contains("additional-search-oneways")){
			((com.gridnine.bof.server.gds.rules.proxy.GDSParametersActions) proxy.getActionSet()).setSearchOW(true);
			proxy.getAppliedRuleCategories().add("additional-search-oneways");
			if(proxy.getAppliedRuleCategories().contains("additional-search-oneways") || proxy.getAppliedRuleCategories().contains("applicable-GDS")){
				proxy.getAppliedRules().add("A2F077E2-9EEC-4D14-A20C-4F2B469798B8");
				proxy.setRoundingMode("NONE");
				proxy.setRoundingValue("V_1");
			}
		   }
		}
end

#Применимые ГДС для rostel
rule "rule 6"
salience -6
	when
		proxy: com.gridnine.bof.server.rules.RuleProxy (
			proxyType == "GDS_PARAMETERS"
		)
		propSet: com.gridnine.bof.server.gds.rules.proxy.GDSParametersProperties(
			propSet.partnerCode == "rostel"
		) from proxy.getPropertySet()
	then
		if(!(proxy.getAppliedRuleCategories().contains("additional-search-oneways") || proxy.getAppliedRuleCategories().contains("applicable-GDS"))){
		   if(!proxy.getAppliedRuleCategories().contains("applicable-GDS")){
			((com.gridnine.bof.server.gds.rules.proxy.GDSParametersActions) proxy.getActionSet()).addApplicableGDS("GALILEO");
			proxy.getAppliedRuleCategories().add("applicable-GDS");
			if(proxy.getAppliedRuleCategories().contains("additional-search-oneways") || proxy.getAppliedRuleCategories().contains("applicable-GDS")){
				proxy.getAppliedRules().add("7BE009E2-24D2-41A2-8C63-4BDF9CFEBAB3");
				proxy.setRoundingMode("NONE");
				proxy.setRoundingValue("V_1");
			}
		   }
		   if(!proxy.getAppliedRuleCategories().contains("additional-search-oneways")){
			((com.gridnine.bof.server.gds.rules.proxy.GDSParametersActions) proxy.getActionSet()).setSearchOW(true);
			proxy.getAppliedRuleCategories().add("additional-search-oneways");
			if(proxy.getAppliedRuleCategories().contains("additional-search-oneways") || proxy.getAppliedRuleCategories().contains("applicable-GDS")){
				proxy.getAppliedRules().add("7BE009E2-24D2-41A2-8C63-4BDF9CFEBAB3");
				proxy.setRoundingMode("NONE");
				proxy.setRoundingValue("V_1");
			}
		   }
		}
end

#Применимые ГДС для comerapp
rule "rule 7"
salience -7
	when
		proxy: com.gridnine.bof.server.rules.RuleProxy (
			proxyType == "GDS_PARAMETERS"
		)
		propSet: com.gridnine.bof.server.gds.rules.proxy.GDSParametersProperties(
			propSet.partnerCode == "comerapp"
		) from proxy.getPropertySet()
	then
		if(!(proxy.getAppliedRuleCategories().contains("additional-search-oneways") || proxy.getApplied...