package ru.galuzin.drools_test;
 
import ru.galuzin.drools_test.Machine;
import ru.galuzin.drools_test.Test;
import ru.galuzin.drools_test.TestDAO;
import java.util.Calendar;
import java.sql.Timestamp;
global TestDAO testDAO;

function void setTestsDueTime(Machine machine, int numberOfDays) {
	setDueTime(machine, Calendar.DATE, numberOfDays);
} 
	
function void setDueTime(Machine machine, int field, int amount) {
	Calendar calendar = Calendar.getInstance();
	calendar.setTime(machine.getCreationTs());
	calendar.add(field, amount);
	machine.setTestsDueTime(new Timestamp(calendar.getTimeInMillis()));
}

rule "Tests for type2, DNS server machine"
salience 100
when
    machine : Machine(functions == "CHILD")
then
	Test test5 = testDAO.findByKey(Test.TEST5);
	Test test4 = testDAO.findByKey(Test.TEST4);
	machine.getTests().add(test5);
	machine.getTests().add(test4);
end
